"""OpenSim's own CENTRAL DIFFERENCE of its own path length.

# Why this exists, when `opensim_moment_arms.txt` already holds moment arms

`GeometryPath::computeMomentArm` does not differentiate the path length. It asks
`MomentArmSolver` for the generalized force a unit tension along the CURRENT
path produces, with the wrap points held fixed on the bodies they landed on.
For a path that varies smoothly with q that equals -dL/dq (the envelope
theorem). Where the wrap solution is marginal it does not, and the gap is large:
measured on the shipped model,

    TR2_l   / L2_L3_FE  at spine_flexed:  analytic +0.002252, central -0.005274
    gasmed_r/ knee_angle_r at neutral:    analytic +0.021761, central +0.004891

`MomentArmComputer` computes r = -dL/dq by central difference at eps = 1e-4 rad.
Comparing it against the analytic column measures TWO things at once -- whether
the wrap solver is right, and whether OpenSim's two definitions agree -- and the
second one is not this project's to fix. This file dumps the definition-matched
column so the first can be gated on its own.

Read-only against `BioMotion/Resources/FullBody.osim`. Poses come from the
committed fixture, so both references describe byte-identical configurations.

    uv run --python .venv python dump_finite_difference.py \
        --out ../../BioMotionTests/Fixtures/opensim_moment_arms_fd.txt
"""

from __future__ import annotations

import argparse
import os
import sys

import osim_model as M

FIXTURE = os.path.join(
    M.REPO_ROOT, "BioMotionTests", "Fixtures", "opensim_moment_arms.txt"
)
FORMAT_ID = "biomotion-osim-momentarm-fd-v1"
EPS = 1e-4


def read_reference():
    """(coordinate names, [(pose id, values)], {muscle: [coordinates]})."""
    coordinates = None
    poses = []
    muscles = {}
    order = []
    with open(FIXTURE, "r", encoding="ascii") as handle:
        for line in handle:
            fields = line.rstrip("\n").split(" ")
            if fields[0] == "coordinates":
                coordinates = fields[1:]
            elif fields[0] == "pose":
                poses.append((fields[1], [float(v) for v in fields[2:]]))
            elif fields[0] == "muscle":
                name = fields[1]
                carries_wrap = fields[2] == "1"
                count = int(fields[3])
                if carries_wrap:
                    muscles[name] = fields[4:4 + count]
                    order.append(name)
            elif fields[0] == "row":
                break
    if coordinates is None:
        raise SystemExit(f"{FIXTURE} has no `coordinates` header")
    return coordinates, poses, muscles, order


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--eps", type=float, default=EPS)
    args = parser.parse_args()

    coordinate_names, poses, spanned, muscle_order = read_reference()
    model, state, _ = M.load_model()

    coordinate_set = model.getCoordinateSet()
    coordinate_by_name = {
        coordinate_set.get(i).getName(): coordinate_set.get(i)
        for i in range(coordinate_set.getSize())
    }
    missing = [n for n in coordinate_names if n not in coordinate_by_name]
    if missing:
        raise SystemExit(f"the fixture names coordinates the model lacks: {missing}")

    paths = {name: model.getMuscles().get(name).getGeometryPath()
             for name in muscle_order}

    # Every coordinate any wrapped muscle spans. Perturbing one coordinate and
    # reading ALL of their lengths costs one realization instead of one per
    # (muscle, coordinate) pair.
    driving = sorted({c for coords in spanned.values() for c in coords})

    with open(args.out, "w", encoding="ascii") as out:
        out.write("# OpenSim 4.6 central difference of its OWN path length,\n")
        out.write("# -(L(q+eps) - L(q-eps)) / (2 eps), on the muscles that carry a\n")
        out.write("# PathWrap. Generated by tools/opensim_ref/dump_finite_difference.py.\n")
        out.write("# Poses are the ids of BioMotionTests/Fixtures/opensim_moment_arms.txt.\n")
        out.write(f"format {FORMAT_ID}\n")
        out.write(f"eps {args.eps:.9f}\n")
        out.write(f"poses {len(poses)}\n")
        out.write(f"muscles {len(muscle_order)}\n")
        for name in muscle_order:
            coords = spanned[name]
            out.write(f"muscle {name} {len(coords)} " + " ".join(coords) + "\n")
        for pose_index, (pose_id, values) in enumerate(poses):
            out.write(f"pose {pose_id}\n")
            named = dict(zip(coordinate_names, values))
            M.set_pose(model, state, named)
            derivatives = {name: {} for name in muscle_order}
            for coordinate_name in driving:
                coordinate = coordinate_by_name[coordinate_name]
                # The value the model is ACTUALLY holding, not the one asked for.
                base = coordinate.getValue(state)
                coordinate.setValue(state, base + args.eps, False)
                model.realizePosition(state)
                plus = {n: paths[n].getLength(state) for n in muscle_order}
                coordinate.setValue(state, base - args.eps, False)
                model.realizePosition(state)
                minus = {n: paths[n].getLength(state) for n in muscle_order}
                coordinate.setValue(state, base, False)
                model.realizePosition(state)
                for name in muscle_order:
                    if coordinate_name in spanned[name]:
                        derivatives[name][coordinate_name] = (
                            -(plus[name] - minus[name]) / (2.0 * args.eps)
                        )
            for muscle_index, name in enumerate(muscle_order):
                row = [f"{derivatives[name][c]:.9f}" for c in spanned[name]]
                out.write(f"row {pose_index} {muscle_index} " + " ".join(row) + "\n")
            print(f"{pose_index + 1}/{len(poses)} {pose_id}", file=sys.stderr)

    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
