import Foundation

/// OpenSim's own moment arms and path lengths for `FullBody.osim`.
///
/// # What this is for
///
/// `MomentArmComputer` does not implement path WRAPPING. It counts the
/// `PathWrap` references it is ignoring (`unmodelledPathWraps`) and then takes
/// a straight line where the real muscle wraps around bone. Until now this
/// project had no reference to say how wrong that is, so every judgement about
/// it was an argument rather than a measurement.
///
/// This fixture is that reference. It is generated by
/// `tools/opensim_ref/dump_reference.py` + `analyse.py --write-fixture` from
/// the OpenSim 4.6 Python API reading the SAME `BioMotion/Resources/FullBody.osim`
/// the app ships, at a set of poses that includes flexed running configurations,
/// a deep squat, and one-dimensional sweeps through the range of each sagittal
/// lower-limb coordinate.
///
/// Two columns per number:
///
/// - `...WrapOn`  — OpenSim with all 76 `PathWrap`s solved. **The reference.**
/// - `...WrapOff` — the same model with every `WrapObject` deactivated, so each
///   path is the straight polyline through its path points. That is the
///   shortcut the shipped code takes, computed inside OpenSim's own numerics,
///   so the gap between the two columns isolates the missing wrap solver from
///   every other difference between the two implementations.
///
/// # Nothing here force-unwraps a parsed value
///
/// Same rule as `GaitClipFixture`, same scanners (`FixtureScanner`): a
/// malformed file produces a `LoadError` a test can assert on, never a trap
/// that takes the whole test target down.
enum OpenSimReferenceFixture {

    static let formatId = "biomotion-osim-momentarm-v1"
    static let resourceName = "opensim_moment_arms"
    static let resourceSubdirectory = "Fixtures"

    /// One sampled configuration. `values` is parallel to `Table.coordinateNames`
    /// and holds what the model ACTUALLY held after the pose was applied, in
    /// radians (metres for `pelvis_tx`/`ty`/`tz`) — not what the generator asked
    /// for.
    struct Pose {
        let id: String
        let values: [Double]
    }

    /// A muscle and the coordinates it structurally spans, in the order its
    /// moment-arm columns appear.
    struct Muscle {
        let name: String
        /// Whether the muscle carries at least one `PathWrap` in the .osim.
        /// DECLARED by the generator, never inferred from the numbers: a wrap
        /// that happens not to engage at any sampled pose still belongs to a
        /// muscle whose path is unmodelled.
        let carriesPathWrap: Bool
        let coordinates: [String]
    }

    /// One (pose, muscle) sample.
    struct Row {
        let poseIndex: Int
        let muscleIndex: Int
        /// How many `PathWrapPoint`s OpenSim inserted at this pose. **Zero means
        /// the wrap is not engaged here**, so the straight line is momentarily
        /// the right answer — and a pair of adjacent sweep poses that differ in
        /// this flag brackets the discontinuity a centred finite difference
        /// must not straddle.
        let wrapPoints: Int
        let lengthWrapOn: Double
        let lengthWrapOff: Double
        /// Parallel to `Table.muscles[muscleIndex].coordinates`.
        let momentArmsWrapOn: [Double]
        let momentArmsWrapOff: [Double]
    }

    struct Table {
        let coordinateNames: [String]
        let poses: [Pose]
        let muscles: [Muscle]
        let rows: [Row]

        /// `rows` is dense and ordered pose-major, but nothing downstream should
        /// depend on that, so the lookup is explicit.
        func row(pose: Int, muscle: Int) -> Row? {
            guard pose >= 0, pose < poses.count, muscle >= 0, muscle < muscles.count else {
                return nil
            }
            let index = pose * muscles.count + muscle
            guard index < rows.count else { return nil }
            let candidate = rows[index]
            guard candidate.poseIndex == pose, candidate.muscleIndex == muscle else {
                return rows.first { $0.poseIndex == pose && $0.muscleIndex == muscle }
            }
            return candidate
        }

        func muscleIndex(_ name: String) -> Int? {
            muscles.firstIndex { $0.name == name }
        }

        func poseIndex(_ id: String) -> Int? {
            poses.firstIndex { $0.id == id }
        }

        /// Coordinate name -> value, for feeding
        /// `MomentArmComputer.computeMomentArms(withJointAngles:dofNames:)`.
        func coordinateValues(poseIndex: Int) -> [String: Double] {
            guard poseIndex >= 0, poseIndex < poses.count else { return [:] }
            var out: [String: Double] = [:]
            for (index, name) in coordinateNames.enumerated() {
                out[name] = poses[poseIndex].values[index]
            }
            return out
        }
    }

    // MARK: - Errors

    enum LoadError: Error, Equatable, CustomStringConvertible {
        case fileNotFound(String)
        case fileUnreadable(name: String, reason: String)
        case notText(name: String)
        case notASCII(line: Int, byte: UInt8)
        case missingHeaderLine(expectedKey: String)
        case badHeaderKey(line: Int, expected: String, got: String)
        case unsupportedFormat(line: Int, got: String)
        case emptyHeaderValue(line: Int, key: String)
        case badInteger(line: Int, field: Int, text: String)
        case badDecimal(line: Int, field: Int, text: String)
        case badFieldCount(line: Int, expected: Int, got: Int)
        case unknownRecord(line: Int, tag: String)
        case indexOutOfRange(line: Int, field: String, value: Int, count: Int)
        case duplicateName(line: Int, name: String)
        case countMismatch(kind: String, declared: Int, found: Int)
        case rowOutOfOrder(line: Int, expectedPose: Int, expectedMuscle: Int)

        var description: String {
            switch self {
            case .fileNotFound(let name):
                return "no fixture resource named \(name) in the test bundle"
            case .fileUnreadable(let name, let reason):
                return "fixture \(name) could not be read: \(reason)"
            case .notText(let name):
                return "fixture \(name) is not decodable text"
            case .notASCII(let line, let byte):
                return "line \(line): byte 0x\(String(byte, radix: 16)) is not printable ASCII"
            case .missingHeaderLine(let key):
                return "file ended before the `\(key)` header line"
            case .badHeaderKey(let line, let expected, let got):
                return "line \(line): expected header key `\(expected)`, got `\(got)`"
            case .unsupportedFormat(let line, let got):
                return "line \(line): format `\(got)` is not `\(OpenSimReferenceFixture.formatId)`"
            case .emptyHeaderValue(let line, let key):
                return "line \(line): header `\(key)` has no value"
            case .badInteger(let line, let field, let text):
                return "line \(line) field \(field): `\(text)` is not a plain decimal integer"
            case .badDecimal(let line, let field, let text):
                return "line \(line) field \(field): `\(text)` is not a plain decimal number"
            case .badFieldCount(let line, let expected, let got):
                return "line \(line): expected \(expected) fields, got \(got)"
            case .unknownRecord(let line, let tag):
                return "line \(line): unknown record tag `\(tag)`"
            case .indexOutOfRange(let line, let field, let value, let count):
                return "line \(line): \(field) \(value) is outside 0..<\(count)"
            case .duplicateName(let line, let name):
                return "line \(line): `\(name)` is declared twice"
            case .countMismatch(let kind, let declared, let found):
                return "header declares \(declared) \(kind), file holds \(found)"
            case .rowOutOfOrder(let line, let pose, let muscle):
                return "line \(line): expected the row for pose \(pose) muscle \(muscle)"
            }
        }
    }

    // MARK: - Loading

    static func load(bundle: Bundle) throws -> Table {
        guard let url = bundle.url(forResource: resourceName, withExtension: "txt",
                                   subdirectory: resourceSubdirectory) else {
            throw LoadError.fileNotFound("\(resourceSubdirectory)/\(resourceName).txt")
        }
        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            throw LoadError.fileUnreadable(name: resourceName, reason: "\(error)")
        }
        guard let text = String(data: data, encoding: .utf8) else {
            throw LoadError.notText(name: resourceName)
        }
        return try parse(text)
    }

    // MARK: - Parsing

    private static let headerKeys = ["format", "coordinates", "poses", "muscles"]

    /// Grammar, checked line by line:
    ///
    ///     '#' comment | blank                      anywhere, ignored
    ///     format      biomotion-osim-momentarm-v1
    ///     coordinates <name> ...                   169 of them
    ///     poses       <count>
    ///     muscles     <count>
    ///     pose   <id> <value>*                     one per coordinate
    ///     muscle <name> <carriesPathWrap 0|1> <k> <coordinate>*   k of them
    ///     row    <poseIndex> <muscleIndex> <wrapPoints>
    ///            <lengthOn> <lengthOff> <rOn>*k <rOff>*k
    ///
    /// Integers are `[0-9]+`, decimals `-?[0-9]+.[0-9]+`, single-space separated.
    static func parse(_ text: String) throws -> Table {
        var coordinateNames: [String] = []
        var declaredPoses = 0
        var declaredMuscles = 0
        var headersSeen = 0
        var poses: [Pose] = []
        var muscles: [Muscle] = []
        var rows: [Row] = []
        var seenPoseIds = Set<String>()
        var seenMuscleNames = Set<String>()

        for (index, rawLine) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            let lineNumber = index + 1
            var line = rawLine
            if line.hasSuffix("\r") { line = line.dropLast() }

            if let offending = FixtureScanner.firstNonASCIIByte(line) {
                throw LoadError.notASCII(line: lineNumber, byte: offending)
            }
            if line.isEmpty || line.hasPrefix("#") { continue }

            let fields = line.split(separator: " ", omittingEmptySubsequences: false)

            if headersSeen < headerKeys.count {
                let key = headerKeys[headersSeen]
                guard let got = fields.first, got == key else {
                    throw LoadError.badHeaderKey(line: lineNumber, expected: key,
                                                 got: String(fields.first ?? ""))
                }
                let values = fields.dropFirst().map(String.init)
                guard !values.isEmpty, !values.contains(where: { $0.isEmpty }) else {
                    throw LoadError.emptyHeaderValue(line: lineNumber, key: key)
                }
                switch key {
                case "format":
                    guard values.count == 1, values[0] == formatId else {
                        throw LoadError.unsupportedFormat(line: lineNumber,
                                                          got: values.joined(separator: " "))
                    }
                case "coordinates":
                    coordinateNames = values
                case "poses":
                    guard values.count == 1,
                          let count = FixtureScanner.strictInt(Substring(values[0])) else {
                        throw LoadError.badInteger(line: lineNumber, field: 1,
                                                   text: values.joined(separator: " "))
                    }
                    declaredPoses = count
                    poses.reserveCapacity(count)
                default:
                    guard values.count == 1,
                          let count = FixtureScanner.strictInt(Substring(values[0])) else {
                        throw LoadError.badInteger(line: lineNumber, field: 1,
                                                   text: values.joined(separator: " "))
                    }
                    declaredMuscles = count
                    muscles.reserveCapacity(count)
                    rows.reserveCapacity(count * declaredPoses)
                }
                headersSeen += 1
                continue
            }

            guard let tag = fields.first else {
                throw LoadError.unknownRecord(line: lineNumber, tag: "")
            }

            switch tag {
            case "pose":
                let expected = 2 + coordinateNames.count
                guard fields.count == expected else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: expected,
                                                  got: fields.count)
                }
                let id = String(fields[1])
                guard seenPoseIds.insert(id).inserted else {
                    throw LoadError.duplicateName(line: lineNumber, name: id)
                }
                var values: [Double] = []
                values.reserveCapacity(coordinateNames.count)
                for field in 2..<expected {
                    guard let value = FixtureScanner.strictDecimal(fields[field]) else {
                        throw LoadError.badDecimal(line: lineNumber, field: field,
                                                   text: String(fields[field]))
                    }
                    values.append(value)
                }
                poses.append(Pose(id: id, values: values))

            case "muscle":
                guard fields.count >= 4 else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: 4,
                                                  got: fields.count)
                }
                let name = String(fields[1])
                guard seenMuscleNames.insert(name).inserted else {
                    throw LoadError.duplicateName(line: lineNumber, name: name)
                }
                guard let wrapFlag = FixtureScanner.strictInt(fields[2]), wrapFlag <= 1 else {
                    throw LoadError.badInteger(line: lineNumber, field: 2,
                                               text: String(fields[2]))
                }
                guard let count = FixtureScanner.strictInt(fields[3]) else {
                    throw LoadError.badInteger(line: lineNumber, field: 3,
                                               text: String(fields[3]))
                }
                let expected = 4 + count
                guard fields.count == expected else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: expected,
                                                  got: fields.count)
                }
                let coordinates = fields[4..<expected].map(String.init)
                for coordinate in coordinates where !coordinateNames.contains(coordinate) {
                    throw LoadError.unknownRecord(line: lineNumber, tag: coordinate)
                }
                muscles.append(Muscle(name: name, carriesPathWrap: wrapFlag == 1,
                                      coordinates: coordinates))

            case "row":
                guard fields.count >= 6 else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: 6,
                                                  got: fields.count)
                }
                guard let poseIndex = FixtureScanner.strictInt(fields[1]) else {
                    throw LoadError.badInteger(line: lineNumber, field: 1,
                                               text: String(fields[1]))
                }
                guard let muscleIndex = FixtureScanner.strictInt(fields[2]) else {
                    throw LoadError.badInteger(line: lineNumber, field: 2,
                                               text: String(fields[2]))
                }
                guard poseIndex < poses.count else {
                    throw LoadError.indexOutOfRange(line: lineNumber, field: "poseIndex",
                                                    value: poseIndex, count: poses.count)
                }
                guard muscleIndex < muscles.count else {
                    throw LoadError.indexOutOfRange(line: lineNumber, field: "muscleIndex",
                                                    value: muscleIndex, count: muscles.count)
                }
                // Dense and ordered, so `Table.row(pose:muscle:)` can index
                // rather than search — and a generator that ever emits a hole
                // is caught here instead of producing a silently short table.
                let expectedPose = rows.count / muscles.count
                let expectedMuscle = rows.count % muscles.count
                guard poseIndex == expectedPose, muscleIndex == expectedMuscle else {
                    throw LoadError.rowOutOfOrder(line: lineNumber,
                                                  expectedPose: expectedPose,
                                                  expectedMuscle: expectedMuscle)
                }
                guard let wrapPoints = FixtureScanner.strictInt(fields[3]) else {
                    throw LoadError.badInteger(line: lineNumber, field: 3,
                                               text: String(fields[3]))
                }
                let arity = muscles[muscleIndex].coordinates.count
                let expected = 6 + 2 * arity
                guard fields.count == expected else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: expected,
                                                  got: fields.count)
                }
                var numbers: [Double] = []
                numbers.reserveCapacity(2 + 2 * arity)
                for field in 4..<expected {
                    guard let value = FixtureScanner.strictDecimal(fields[field]) else {
                        throw LoadError.badDecimal(line: lineNumber, field: field,
                                                   text: String(fields[field]))
                    }
                    numbers.append(value)
                }
                rows.append(Row(poseIndex: poseIndex,
                                muscleIndex: muscleIndex,
                                wrapPoints: wrapPoints,
                                lengthWrapOn: numbers[0],
                                lengthWrapOff: numbers[1],
                                momentArmsWrapOn: Array(numbers[2..<(2 + arity)]),
                                momentArmsWrapOff: Array(numbers[(2 + arity)...])))

            default:
                throw LoadError.unknownRecord(line: lineNumber, tag: String(tag))
            }
        }

        guard headersSeen == headerKeys.count else {
            throw LoadError.missingHeaderLine(expectedKey: headerKeys[headersSeen])
        }
        guard poses.count == declaredPoses else {
            throw LoadError.countMismatch(kind: "poses", declared: declaredPoses,
                                          found: poses.count)
        }
        guard muscles.count == declaredMuscles else {
            throw LoadError.countMismatch(kind: "muscles", declared: declaredMuscles,
                                          found: muscles.count)
        }
        guard rows.count == declaredPoses * declaredMuscles else {
            throw LoadError.countMismatch(kind: "rows",
                                          declared: declaredPoses * declaredMuscles,
                                          found: rows.count)
        }
        return Table(coordinateNames: coordinateNames, poses: poses,
                     muscles: muscles, rows: rows)
    }
}
