import Foundation

/// OpenSim's own CENTRAL DIFFERENCE of its own path length, on the 66 muscles
/// that carry a `PathWrap`.
///
/// # Why a second reference
///
/// `OpenSimReferenceFixture`'s moment-arm columns come from
/// `GeometryPath::computeMomentArm`, which does NOT differentiate the path
/// length: it asks `MomentArmSolver` for the generalized force a unit tension
/// along the current path produces, with the wrap points held fixed on their
/// bodies. That equals `-dL/dq` for a path that varies smoothly with q. Where
/// the wrap solution is marginal it does not, and the gap is not small —
/// measured on the shipped model,
///
///     TR2_l   / L2_L3_FE    at spine_flexed: analytic +0.002252, central −0.005274
///     gasmed_r/ knee_angle_r at neutral:     analytic +0.021761, central +0.004891
///
/// `MomentArmComputer` computes `r = −dL/dq` by central difference at the same
/// `eps`. Gating it against the analytic column measures two things at once, and
/// the second — whether OpenSim's two definitions agree with each other — is not
/// this project's to fix. This column isolates the first.
///
/// Generated by `tools/opensim_ref/dump_finite_difference.py` in 7 s. Poses are
/// named by the ID they carry in `opensim_moment_arms.txt`, so both references
/// describe the same configurations without duplicating 173 × 169 values.
enum OpenSimFiniteDifferenceFixture {

    static let formatId = "biomotion-osim-momentarm-fd-v1"
    static let resourceName = "opensim_moment_arms_fd"
    static let resourceSubdirectory = "Fixtures"

    struct Muscle {
        let name: String
        let coordinates: [String]
    }

    struct Row {
        let poseIndex: Int
        let muscleIndex: Int
        /// Parallel to `Table.muscles[muscleIndex].coordinates`.
        let momentArms: [Double]
    }

    struct Table {
        /// Step used for the difference, in radians. A consumer differentiating
        /// at a DIFFERENT step is not comparing like with like.
        let eps: Double
        let poseIds: [String]
        let muscles: [Muscle]
        let rows: [Row]

        func row(pose: Int, muscle: Int) -> Row? {
            guard pose >= 0, pose < poseIds.count,
                  muscle >= 0, muscle < muscles.count else { return nil }
            let index = pose * muscles.count + muscle
            guard index < rows.count else { return nil }
            let candidate = rows[index]
            guard candidate.poseIndex == pose, candidate.muscleIndex == muscle else {
                return rows.first { $0.poseIndex == pose && $0.muscleIndex == muscle }
            }
            return candidate
        }

        func muscleIndex(_ name: String) -> Int? { muscles.firstIndex { $0.name == name } }
        func poseIndex(_ id: String) -> Int? { poseIds.firstIndex(of: id) }
    }

    enum LoadError: Error, Equatable, CustomStringConvertible {
        case fileNotFound(String)
        case fileUnreadable(name: String, reason: String)
        case notText(name: String)
        case notASCII(line: Int, byte: UInt8)
        case badHeaderKey(line: Int, expected: String, got: String)
        case unsupportedFormat(line: Int, got: String)
        case badInteger(line: Int, field: Int, text: String)
        case badDecimal(line: Int, field: Int, text: String)
        case badFieldCount(line: Int, expected: Int, got: Int)
        case unknownRecord(line: Int, tag: String)
        case duplicateName(line: Int, name: String)
        case countMismatch(kind: String, declared: Int, found: Int)
        case rowOutOfOrder(line: Int, expectedPose: Int, expectedMuscle: Int)
        case missingHeaderLine(expectedKey: String)

        var description: String {
            switch self {
            case .fileNotFound(let name): return "no fixture resource named \(name)"
            case .fileUnreadable(let name, let reason):
                return "fixture \(name) could not be read: \(reason)"
            case .notText(let name): return "fixture \(name) is not decodable text"
            case .notASCII(let line, let byte):
                return "line \(line): byte 0x\(String(byte, radix: 16)) is not printable ASCII"
            case .badHeaderKey(let line, let expected, let got):
                return "line \(line): expected header key `\(expected)`, got `\(got)`"
            case .unsupportedFormat(let line, let got):
                return "line \(line): format `\(got)` is not `\(formatId)`"
            case .badInteger(let line, let field, let text):
                return "line \(line) field \(field): `\(text)` is not a plain decimal integer"
            case .badDecimal(let line, let field, let text):
                return "line \(line) field \(field): `\(text)` is not a plain decimal number"
            case .badFieldCount(let line, let expected, let got):
                return "line \(line): expected \(expected) fields, got \(got)"
            case .unknownRecord(let line, let tag):
                return "line \(line): unknown record tag `\(tag)`"
            case .duplicateName(let line, let name):
                return "line \(line): `\(name)` is declared twice"
            case .countMismatch(let kind, let declared, let found):
                return "header declares \(declared) \(kind), file holds \(found)"
            case .rowOutOfOrder(let line, let pose, let muscle):
                return "line \(line): expected the row for pose \(pose) muscle \(muscle)"
            case .missingHeaderLine(let key):
                return "file ended before the `\(key)` header line"
            }
        }
    }

    static func load(bundle: Bundle) throws -> Table {
        guard let url = bundle.url(forResource: resourceName, withExtension: "txt",
                                   subdirectory: resourceSubdirectory) else {
            throw LoadError.fileNotFound("\(resourceSubdirectory)/\(resourceName).txt")
        }
        let data: Data
        do {
            data = try Data(contentsOf: url)
        } catch {
            throw LoadError.fileUnreadable(name: resourceName, reason: "\(error)")
        }
        guard let text = String(data: data, encoding: .utf8) else {
            throw LoadError.notText(name: resourceName)
        }
        return try parse(text)
    }

    private static let headerKeys = ["format", "eps", "poses", "muscles"]

    /// Same grammar rules as `OpenSimReferenceFixture`, same scanners: nothing
    /// here force-unwraps a parsed value, so a malformed file throws instead of
    /// taking the test host down.
    ///
    ///     format  biomotion-osim-momentarm-fd-v1
    ///     eps     <decimal>
    ///     poses   <count>
    ///     muscles <count>
    ///     muscle  <name> <k> <coordinate>*k
    ///     pose    <id>
    ///     row     <poseIndex> <muscleIndex> <r>*k
    static func parse(_ text: String) throws -> Table {
        var eps = 0.0
        var declaredPoses = 0
        var declaredMuscles = 0
        var headersSeen = 0
        var poseIds: [String] = []
        var muscles: [Muscle] = []
        var rows: [Row] = []
        var seenPoseIds = Set<String>()
        var seenMuscleNames = Set<String>()

        for (index, rawLine) in text.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            let lineNumber = index + 1
            var line = rawLine
            if line.hasSuffix("\r") { line = line.dropLast() }
            if let offending = FixtureScanner.firstNonASCIIByte(line) {
                throw LoadError.notASCII(line: lineNumber, byte: offending)
            }
            if line.isEmpty || line.hasPrefix("#") { continue }

            let fields = line.split(separator: " ", omittingEmptySubsequences: false)

            if headersSeen < headerKeys.count {
                let key = headerKeys[headersSeen]
                guard let got = fields.first, got == key else {
                    throw LoadError.badHeaderKey(line: lineNumber, expected: key,
                                                 got: String(fields.first ?? ""))
                }
                guard fields.count == 2 else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: 2,
                                                  got: fields.count)
                }
                switch key {
                case "format":
                    guard fields[1] == formatId else {
                        throw LoadError.unsupportedFormat(line: lineNumber,
                                                          got: String(fields[1]))
                    }
                case "eps":
                    guard let value = FixtureScanner.strictDecimal(fields[1]), value > 0 else {
                        throw LoadError.badDecimal(line: lineNumber, field: 1,
                                                   text: String(fields[1]))
                    }
                    eps = value
                case "poses":
                    guard let count = FixtureScanner.strictInt(fields[1]) else {
                        throw LoadError.badInteger(line: lineNumber, field: 1,
                                                   text: String(fields[1]))
                    }
                    declaredPoses = count
                default:
                    guard let count = FixtureScanner.strictInt(fields[1]) else {
                        throw LoadError.badInteger(line: lineNumber, field: 1,
                                                   text: String(fields[1]))
                    }
                    declaredMuscles = count
                }
                headersSeen += 1
                continue
            }

            guard let tag = fields.first else {
                throw LoadError.unknownRecord(line: lineNumber, tag: "")
            }

            switch tag {
            case "muscle":
                guard fields.count >= 3 else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: 3,
                                                  got: fields.count)
                }
                let name = String(fields[1])
                guard seenMuscleNames.insert(name).inserted else {
                    throw LoadError.duplicateName(line: lineNumber, name: name)
                }
                guard let count = FixtureScanner.strictInt(fields[2]) else {
                    throw LoadError.badInteger(line: lineNumber, field: 2,
                                               text: String(fields[2]))
                }
                let expected = 3 + count
                guard fields.count == expected else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: expected,
                                                  got: fields.count)
                }
                muscles.append(Muscle(name: name,
                                      coordinates: fields[3..<expected].map(String.init)))

            case "pose":
                guard fields.count == 2 else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: 2,
                                                  got: fields.count)
                }
                let id = String(fields[1])
                guard seenPoseIds.insert(id).inserted else {
                    throw LoadError.duplicateName(line: lineNumber, name: id)
                }
                poseIds.append(id)

            case "row":
                guard fields.count >= 3 else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: 3,
                                                  got: fields.count)
                }
                guard let poseIndex = FixtureScanner.strictInt(fields[1]) else {
                    throw LoadError.badInteger(line: lineNumber, field: 1,
                                               text: String(fields[1]))
                }
                guard let muscleIndex = FixtureScanner.strictInt(fields[2]),
                      muscleIndex < muscles.count else {
                    throw LoadError.badInteger(line: lineNumber, field: 2,
                                               text: String(fields[2]))
                }
                let expectedPose = muscles.isEmpty ? 0 : rows.count / muscles.count
                let expectedMuscle = muscles.isEmpty ? 0 : rows.count % muscles.count
                guard poseIndex == expectedPose, muscleIndex == expectedMuscle else {
                    throw LoadError.rowOutOfOrder(line: lineNumber,
                                                  expectedPose: expectedPose,
                                                  expectedMuscle: expectedMuscle)
                }
                let arity = muscles[muscleIndex].coordinates.count
                let expected = 3 + arity
                guard fields.count == expected else {
                    throw LoadError.badFieldCount(line: lineNumber, expected: expected,
                                                  got: fields.count)
                }
                var values: [Double] = []
                values.reserveCapacity(arity)
                for field in 3..<expected {
                    guard let value = FixtureScanner.strictDecimal(fields[field]) else {
                        throw LoadError.badDecimal(line: lineNumber, field: field,
                                                   text: String(fields[field]))
                    }
                    values.append(value)
                }
                rows.append(Row(poseIndex: poseIndex, muscleIndex: muscleIndex,
                                momentArms: values))

            default:
                throw LoadError.unknownRecord(line: lineNumber, tag: String(tag))
            }
        }

        guard headersSeen == headerKeys.count else {
            throw LoadError.missingHeaderLine(expectedKey: headerKeys[headersSeen])
        }
        guard poseIds.count == declaredPoses else {
            throw LoadError.countMismatch(kind: "poses", declared: declaredPoses,
                                          found: poseIds.count)
        }
        guard muscles.count == declaredMuscles else {
            throw LoadError.countMismatch(kind: "muscles", declared: declaredMuscles,
                                          found: muscles.count)
        }
        guard rows.count == declaredPoses * declaredMuscles else {
            throw LoadError.countMismatch(kind: "rows",
                                          declared: declaredPoses * declaredMuscles,
                                          found: rows.count)
        }
        return Table(eps: eps, poseIds: poseIds, muscles: muscles, rows: rows)
    }
}
